### ISSUE TITLE
Include User-Filtered Latitude and Longitude in search_view and search_card_view Event Data Sent to Splunk

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#157]
Background:
We use Splunk to store user behavior activities as events, utilizing its HEC API for event collection. Specifically, we track events like user interactions with search results and search card clicks. These events undergo data processing, such as removing invalid behaviors and generating new metrics.

Each Splunk event includes common fields like event_group and event_type.

I've identified an enhancement needed in the event data being sent to Splunk, specifically within the `search_view` and `search_card_view` events. Currently, these events do not include the latitude (`lat`) and longitude (`lon`) values that have been filtered by the user. This is particularly important when the user selects the 'near me' filter.

Including these filtered `lat` and `lon` values in the event data will greatly enhance our ability to analyze user behavior based on geographical preferences and improve the overall functionality of our analytics.

Thank you for considering this enhancement.

**Comment by hamidsarani** [comment]
- Estimate: 2h
- Deadline: 2024-01-29
