### ISSUE TITLE
Add 'Developers' Menu with Submenus to Header Menu

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#158]
I propose the integration of a new menu titled 'توسعه دهندگان' (Developers) into the platform's header menu. This addition aims to enhance accessibility and resource availability for our Farsi-speaking developer community.

Details:
The 'Developers' menu should include the following submenus, all in Farsi:

- وب سرویس ها (Web Services)
- مستندات بازارچه (Marketplace Documentation)
- جامعه توسعه دهندگان (Developer Community)
- گیت هاب پذیرش24 (GitHub Paziresh24)

Each submenu should be properly linked to its respective section or external resource, ensuring a seamless user experience.

**Comment by ebrahimghane** [comment]
link URLs:
توسعه دهندگان
وب سرویس ها (https://developers.paziresh24.com/rest)
مستندات بازارچه (https://developers.paziresh24.com/rest/bazaar)
جامعه توسعه دهندگان (https://community.paziresh24.com/)
گیت هاب پذیرش24 (https://github.com/paziresh24)

**Comment by ebrahimghane** [comment]
note: Menu must be at the end of the menu list.

**Comment by hamidsarani** [comment]
- Estimate: 4h
- Deadline: 2024-01-24

**Comment by AmirhBeigi** [comment]
>  مستندات بازارچه (https://developers.paziresh24.com/rest/bazaar)
Please change link to https://developers.paziresh24.com/apps
