### ISSUE TITLE
Remove Common Cities from Location Selection Filter Modal

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#159]
### Summary:
The current implementation of the location selection filter modal includes a list of common cities. However, since Paziresh24 is now serving all states, the inclusion of common cities has become irrelevant to the user's context. This issue proposes the removal of these common cities from the filter modal to better align with the expanded service coverage.

![image](https://github.com/paziresh24/patient/assets/6231619/6e8d64df-d5c2-455c-8860-f3524f51363c)

### Details:
- **Current Behavior:** The location selection filter modal displays a predefined list of common cities.
- **Proposed Change:** Remove the list of common cities from the location selection filter modal.
- **Reason for Change:** Paziresh24 has expanded its services to encompass all states, making the distinction of common cities less relevant for users. The removal of this list will streamline the user experience and ensure that the filter modal is more universally applicable, regardless of the user's location.

### Expected Outcome:
- A more streamlined and relevant location selection process for users.
- Enhanced usability of the filter modal by eliminating unnecessary or irrelevant options.

### Additional Notes:
- Care should be taken to ensure that the removal of common cities does not affect the overall functionality of the location selection filter.
- Testing should be conducted to confirm that the updated filter modal operates smoothly across all states.

This change is aimed at improving the user experience by simplifying the location selection process and making it more inclusive of all service areas covered by Paziresh24.

**Comment by hamidsarani** [comment]
- Estimate: 2h
- Deadline: 2024-01-24
