### ISSUE TITLE
Implement Loading Animation for 'Near My Location' Button During GPS Data Retrieval

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#160]
#### Summary:
Request to add a loading animation to the 'Near My Location' button within the search suggestion box to enhance user experience during the process of retrieving and sending GPS location data to the server.

#### Details:
- **Feature Request:** Introduce a loading animation adjacent to the 'Near My Location' button.
- **Location:** This feature is specifically for the location selection process inside the search suggestion box.
- **Trigger:** The animation should activate when a user clicks the 'Near My Location' button.
- **Duration:** The animation should remain active until the new location data is received from the GPS and successfully transmitted to the server.
- **Purpose:** The primary goal of this enhancement is to **prevent user indecisiveness** and uncertainty while they are waiting for results based on their location. Currently, there is a lack of visual feedback after clicking the 'Near My Location' button, which can lead to confusion or impatience as users wait for their location-based results.

#### Expected Outcome:
By implementing this feature, we aim to improve the user experience by providing clear visual feedback during the process of location data retrieval. This will help in setting the right expectations for users and reduce any potential confusion or frustration during the wait time.

#### Additional Notes:
- The design and style of the loading animation should be consistent with the existing UI/UX design of the application.
- It is important to ensure that the implementation of this feature does not significantly impact the overall performance of the application.

Looking forward to seeing this enhancement in the application, as it will significantly contribute to a smoother and more intuitive user experience.

**Comment by ebrahimghane** [comment]
Sample video showing a user's indecisiveness when selecting the "near me" button.
https://github.com/paziresh24/patient/assets/6231619/38addba3-3982-4ee9-b9a0-ca305641bf51

**Comment by hamidsarani** [comment]
- Estimate: 6h
- Deadline: 2024-01-30
