### ISSUE TITLE
Clarifying Loading Indicator to improving User Experience in the Appointment Scheduling Process

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#161]
**Issue: Unclear Loading Indicator During User Selection in Appointment Scheduling**

In the appointment scheduling process, specifically at the stage where the user selects their preferred messaging app or presses the 'next' button, a loading indicator appears on the button. However, this loading indicator is not sufficiently clear to users. As a result, users often do not realize that they need to wait and repeatedly touch the messenger or 'next' button.
![image](https://github.com/paziresh24/patient/assets/6231619/3bcc2293-337d-4617-84db-a1dad2b9a4c3)
![image](https://github.com/paziresh24/patient/assets/6231619/a34f2d84-1c2f-425f-9d58-88beef274f9d)

This issue represents a significant UX (User Experience) flaw. There are various ways to address this problem to enhance user understanding and interaction.

**Suggested Solution:**

I recommend implementing one of the following solutions to make the loading step more transparent and user-friendly:

1. Display the loading indicator across the entire screen, making it more evident that a process is ongoing and the user should wait.
2. Alternatively, employ a different method to make this step clearer for the user, such as a more prominent or differently styled loading indicator, or adding a text prompt indicating that the process is in progress.

This improvement is crucial for preventing user confusion and ensuring a smoother, more intuitive interaction with the appointment scheduling feature.

**Comment by hamidsarani** [comment]
- Estimate: 6h
- Deadline: 2024-01-27

**Comment by hamidsarani** [comment]
There is 2 point on this issue:

1. The UX seems wrong, we have ‍‍button that named as `ادامه` and this button has no functionality.
2. We can't find any same design for loading in project to use there.

So, based on these points, we have a suggestion on this issue:

- The messengers button should be selectable with border design for selected one.
- User can select and change the selected option.
- The `ادامه` button should be disabled with a hint to select messenger.
- After user selected the messenger, the button will be enabled.
- After user clicked on `ادامه` button, loading indicator shows as same as current loading.

**Comment by ebrahimghane** [comment]
Thank you for your notes. 
I have a point about Your suggestion: the user needs to make an **additional click**. After selecting their preferred messenger, they are required to click the 'ادامه' button. 
Regarding your second point, @AmirhBeigi may have suggestions for a loading indicator (I believe we previously used a Paziresh24 logo with floating dots). 
Overall, if you have more specific suggestions to improve the current suggestion, I would like to hear them.

**Comment by hamidsarani** [comment]
No, i haven't any suggestion.

In response to your point over previous suggestion, we can set default selected `واتساپ` or **user previously selected messenger**.

**Comment by ebrahimghane** [comment]
![image](https://github.com/paziresh24/patient/assets/6231619/b2f200f8-235b-4010-80e8-910647a20882)
Your mockup suggestion seems fine for implementation. Could you please provide an estimate and a deadline @hamidsarani ?
