### ISSUE TITLE
Feature Request: Location Access Modal/Popover on Search Box Interaction

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#164]
**Summary:**
I would like to propose a feature enhancement for the Paziresh24 platform's frontend. The idea is to introduce a modal, popup, or Popover that requests location access when a user clicks on the search box. This feature aims to facilitate users who are looking for location-based searches, allowing them to grant location access easily without navigating to a separate location filter.

**Details:**
- **User Interaction:** When the user clicks on the search box, a request for location access should be presented in a non-intrusive manner.
- **Design Consideration:** The design should allow users to easily grant location access. It's crucial that the components used cause minimal disruption to the user experience. I suggest using a combination of a Popover and a button for the access request. This way, if the user decides not to grant access, they can continue with their search uninterrupted.
- **Integration with Current Design:** The new feature should seamlessly integrate with the existing design of Paziresh24. This includes matching colors, styles, and the use of Paziresh24's UI components.
- **Touchpoint for Modal Display:** The specific touchpoint where the modal should be displayed is indicated in the attached screenshot.
- **Copywriting:** The copywriting for this feature is shown in the image provided.

This enhancement is intended to streamline the user experience, particularly for those seeking location-based services, and to ensure that the platform remains user-friendly and efficient.

![image](https://github.com/paziresh24/patient/assets/6231619/4bd72a9e-70ad-49c3-b7e3-80e6d3f57aef)
![image](https://github.com/paziresh24/patient/assets/6231619/c8194d90-0d84-47b1-a4e8-aaf8f7b72f4a)

**Comment by ebrahimghane** [comment]
the figma of above design:
https://www.figma.com/file/SU12z9oytTk8Y6uyYCWHKL/PAZIRESH-24?type=design&node-id=328-22074&mode=design
![image](https://github.com/paziresh24/patient/assets/6231619/a8180491-16bc-40c0-90bf-438925ee89d9)

**Comment by hamidsarani** [comment]
Estimate: 16h
Deadline: 2024-02-17

What we should do:

- Show modal everytime user clicked on search box and "Near Me" filter is not enabled
- Type and search is not disabled
- If user clicked on `فعلا نه` modal never shows to user (saved on localStorage)
- If user clicked on `دسترسی می دهم`, "Near Me" filter enabled. like this:

![Screenshot from 2024-02-07 13-41-17](https://github.com/paziresh24/patient/assets/96631586/66b9417d-3c5e-47e9-b907-287750aefad3)

**Comment by mansoure-fallah** [comment]
Estimate: 16h
Deadline: 2024-02-15

when clicked on searchbox open modal.
if user typed anything, modal closed and show suggestions.
if user typed and then clear, show modal again.
if user clicked on "دسترسی میدهم", closed modal and show "near me" filter.
if user clicked on "فعلا نه", closed modal and don't show agian
