### ISSUE TITLE
Add Doctor Ratings Count and Average Rate to Top Doctors Bar in Search Suggestion Box

### ISSUE THREAD

**Issue by ebrahimghane** [paziresh24/patient#196]
**Is your feature request related to a problem? Please describe.**
Currently, the search suggestion box in the Paziresh24 frontend does not display the ratings count and average rate of doctors in the top doctors bar. This omission can make it challenging for users to make informed decisions when selecting a doctor, as they lack immediate access to critical evaluation metrics.

**Describe the solution you'd like**
I propose the addition of both the ratings count and the average rate of each doctor to the top doctors bar within the search suggestion box. This enhancement will provide users with immediate and valuable insights into the doctors' professional standings, aiding them in making more informed choices. The implementation should not require the creation of new UI components; instead, it can leverage the existing rate UI elements used in the search results cards. 

**Additional context**
Attached is a screenshot illustrating the proposed before/after changes to the top doctors bar. This visual aid demonstrates how seamlessly the ratings can be integrated into the existing layout, enhancing user experience without disrupting the current design aesthetic.

![image](https://github.com/paziresh24/patient/assets/6231619/af33d028-a451-4b5a-b68a-161d81781860)

**Comment by hamidsarani** [comment]
Estimate: 5h
Deadline: 1 Day after start

What we should do:
- Add ratings count and the average rate to doctor suggestion box
