### ISSUE TITLE
change the receipt page to blank white page

### ISSUE THREAD

**Issue by hsadeghinejad** [paziresh24/patient#217]
When the patient selects a book, on the billing page, changing the word 'factor' in the URL to 'receipt' results in an error, displaying a blank white page

**Comment by hamidsarani** [comment]
I can't undrestand the issue!

**Comment by hsadeghinejad** [comment]
<img width="914" alt="image" src="https://github.com/paziresh24/patient/assets/38876242/5a80b748-3069-4153-9f78-adda200b5929">


when a user selects a doctor and chooses a time slot to book an appointment, a problem arises if the booking requires payment. Specifically, if the URL parameter changes from "factor" to "receipt" for the payment page, the page displays a blank white screen instead of the intended content. This issue occurs because the system removes access to the doctor's scheduling (referred to as "doctor channels") for bookings that haven't been paid for yet. The frontend of the website expects to receive this scheduling information, but since the backend does not return it for unpaid bookings, an error results, leading to the blank page.

**Comment by hamidsarani** [comment]
Estiamte: 2h
Deadline: 1 Day

Issue:
TypeError in receipt page caused blank page
